### PR TITLE
Webcrypto

### PR DESCRIPTION
**Pull request by henrjk**
This is the PR for issue #7 with cleaned up history.  
The history still reflects version increments made in my for that is from 0.2 to 0.2.5. 
The commits since 0.2.5 are new to this PR mostly to adopt webcrypto-shim from npm which became available now.

### CODE REVIEW

**Comment by henrjk** [comment]
Seems like the travis builds are hitting a rate limit. 
Here is a gist https://gist.github.com/topheman/25241e48a1b4f91ec6d4 which may fix this.

**Comment by henrjk** [comment]
I made changes for the travis to build to work. However this requires configuring a personal github access token which I can't do for the PR.
I created another branch in my fork and also setup a travis build there to make sure it works. This build is at https://travis-ci.org/henrjk/connect-js/builds/120051585

**Comment by henrjk** [comment]
The new section [Github rate limit fix for travis build](https://github.com/henrjk/connect-js/blob/12804c24fddeb7a4005a39c45c2b27de8a626f48/devnotes.md#user-content-github-rate-limit-fix-for-travis-build) describes how to have jspm authenticate with GitHub to avoid rate limits. Some of these steps have already been done in `.travis.yml`. However to make the PR build under the anvilresearch organisation the personal Github access token has to be created under that account and then encrypted using travis for this repository and not my fork. 

Currently the `.travis.yml` file aims to logon with an empty token and so there are login errors in the build instead of rate limit error:

     Unauthorized response for GitHub API.
     Use jspm registry config github to reconfigure the credentials, or update them in your ~/.netrc file. 

As mentioned in my previous comment above this worked for my own travis builds and fork at  https://travis-ci.org/henrjk/connect-js/builds/120051585

**Comment by tomkersten** [comment]
@henrjk any idea how to fix the travis-ci issue on this? i glanced at it quickly and it looks like there was a conflict w/ `fsevents`, but didn't dig in at all...

**Comment by henrjk** [comment]
@tomkersten  The `fsevents` issue should be caused by the travis not being able to login into github. The PR is now configured to do so, but the corresponding github token must be created by the anvilresearch organisation (afaik). Authenticated github access is needed so that jspm does not fail with rate limits as the original builds did. See my comment from 13 days ago for more details.
Let me know if you have additional question. 
I will be offline soon for today. Let me know if you have more questions.

**Comment by tomkersten** [comment]
I'm sorry for not reading that just now...I had glanced over it when you posted it, but thought it had been taken care of. Will investigate.

**Comment by dmitrizagidulin** [comment]
+1 to merging, since this is the right direction to go in.
(I understand that the TravisCI integration / key will need to be sorted out)

**Comment by christiansmith** [comment]
Sorry to everyone this has taken so long. I've been spread pretty thin. It's now merged into the webcrypto-api branch of this repo. We can work out any issues like travis integration in that branch. 

I also want to verify how it works with OIDC Sessions as implemented by Anvil Connect before merging and releasing to npm.

Also, thank you @henrjk very much for your work on this. Huge step forward!

**Comment by dmitrizagidulin** [comment]
Awesome, ok! Will be testing this branch, then.

**Pull request merged**
